# Generated by Django 3.0 on 2019-12-10 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_auto_20191209_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeseries',
            name='Autocorrelation_1',
            field=models.DecimalField(decimal_places=5, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='Autocorrelation_12',
            field=models.DecimalField(decimal_places=5, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='Autocorrelation_2',
            field=models.DecimalField(decimal_places=5, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='Chaos',
            field=models.DecimalField(decimal_places=5, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='Energy',
            field=models.DecimalField(decimal_places=5, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='FFNN',
            field=models.DecimalField(decimal_places=5, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='Kurtosis',
            field=models.DecimalField(decimal_places=5, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='LSTM',
            field=models.DecimalField(decimal_places=5, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='Nonlinearity',
            field=models.DecimalField(decimal_places=5, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='Partial_autocorrelation_1',
            field=models.DecimalField(decimal_places=5, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='Partial_autocorrelation_12',
            field=models.DecimalField(decimal_places=5, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='Partial_autocorrelation_2',
            field=models.DecimalField(decimal_places=5, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='Periodicity',
            field=models.DecimalField(decimal_places=5, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='SelfSimilarity',
            field=models.DecimalField(decimal_places=5, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='Sweekness',
            field=models.DecimalField(decimal_places=5, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='Trend',
            field=models.DecimalField(decimal_places=5, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='Variance',
            field=models.DecimalField(decimal_places=5, max_digits=6, null=True),
        ),
    ]
