# Generated by Django 3.0 on 2019-12-10 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0005_auto_20191209_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSeriesValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=64, null=True)),
                ('values', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
